edition = "2018"
fn_args_layout = "Compressed"
format_strings = true
match_block_trailing_comma = true
reorder_imports = true
spaces_around_ranges = true
use_try_shorthand = true
newline_style = "Native"
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
format_code_in_doc_comments = true
fn_single_line = true