name: Pakken
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - nightly
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy

    - uses: actions-rs/cargo@v1
      with:
        command: build

    - uses: actions-rs/cargo@v1
      with:
        command: test

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
