name: Parser
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build -p parser --verbose
    - name: Run tests
      run: cargo test -p parser --verbose
